### ISSUE TITLE
https://stackoverflow.com/jobs/why-jobs

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/StackOverflow-Dark#114]
Styling is off. But...

```css
.why-jobs-v2 .slanted-background._light-gray::before {
  background-color: #222;
}

.why-jobs-v2 .slanted-background._white::before {
  background-color: #222;
}

.why-jobs-v2 h2,
.why-jobs-v2 h3 {
  color: #aaa;
}

.why-jobs-v2 .developers-first select option {
  background: #000;
  color: #eee;
}
```

Kinda takes care of most of it.

![screenshot-2018-6-15 find your dream developer job - stack overflow](https://user-images.githubusercontent.com/31389848/41491094-09a8a9a0-70ef-11e8-9af0-9bc91f4b6b5a.png)

![screenshot-2018-6-15 find your dream developer job - stack overflow 1](https://user-images.githubusercontent.com/31389848/41491093-098c1182-70ef-11e8-8ca3-b1cdce85545c.png)

I just dindt know if i should add another section but anyway regex is not simple to me.
