### ISSUE TITLE
New reputation card

### ISSUE THREAD

**Issue by franklinyu** [StylishThemes/StackOverflow-Dark#117]
On user activity page such as <https://stackoverflow.com/users/3156906/mclayton?tab=topactivity>, the `div#rep-card-next` is not eligible enough. I suggest

```css
.s-progress__privilege .s-progress--bar {
  background-color: #47865a;
}
```

Or similar dark color. Compare original

![capture-2](https://user-images.githubusercontent.com/3153452/43801114-2ab66598-9a60-11e8-9ea8-5f18ffd8f6b6.PNG)

with proposed

![capture-1](https://user-images.githubusercontent.com/3153452/43801125-35ab03dc-9a60-11e8-9a2c-b859efeca179.PNG)
