### ISSUE TITLE
CODE box color in accepted answers

### ISSUE THREAD

**Issue by tophf** [StylishThemes/StackOverflow-Dark#12]
Code boxes in accepted answers could use a slightly different background color that blends into the surroundings better.

* **Before:**

  ![1-fs8](https://cloud.githubusercontent.com/assets/1310400/7759731/a6d0eee6-001c-11e5-9729-65c65c8ccf17.png)

* **After:**

  ![3-fs8](https://cloud.githubusercontent.com/assets/1310400/7759743/bcf49e98-001c-11e5-8e5d-fda2ca84046d.png)

```css
.accepted-answer pre, .accepted-answer code, .accepted-answer .pln, .accepted-answer .youarehere {
    background: #202A20 !important;
}
```
