### ISSUE TITLE
The text inside the 'Email' and 'Password' textboxes in the login page is almost unreadable because of the yellow background

### ISSUE THREAD

**Issue by darkred** [StylishThemes/StackOverflow-Dark#123]
* **Browser**: Chrome 68.0.3440.106 x64 stable, Stylus 1.4.20, style v3.0.2
* **Operating System**: win10
* **Screenshots**:
![2018-08-26_111141](https://user-images.githubusercontent.com/723651/44626352-5df3ac00-a923-11e8-865a-091a4ab652a2.jpg) ![2018-08-26_111153](https://user-images.githubusercontent.com/723651/44626284-394b0480-a922-11e8-98bc-dbd2663f1683.jpg)

The issue is that the text inside the 'Email' and 'Password' textboxes in the [SO login page](https://stackoverflow.com/users/login) is unreadable because of the yellow background that remains.

* **HTML of the section where the issue occurs**:

Here is a the HTML for the 'Email' textbox:
````html
<input type="email" name="email" id="email" size="30" maxlength="100" placeholder="you@example.org">
````

**Comment by Mottie** [comment]
Hi @darkred!

Those input backgrounds are not yellow by default. Are you using another extension that is adding that background color?

**Comment by darkred** [comment]
No, even if I disable all extensions, they still are yellow.

And, FWIW, in'Edit Profile Settings'|'SITE SETTINGS' group|Preferences:
the only enabled setting is "Enable keyboard shortcuts".
<details>
<summary>screenshot</summary>

![2018-08-26_130005](https://user-images.githubusercontent.com/723651/44627099-cbf2a000-a930-11e8-9760-9e0f6e66a6ba.jpg)
</details>

**Comment by Mottie** [comment]
Would you please look in the dev console and share the style that is applying the yellow background. It must have an `!important` flag and have more specificity than ours (`input:not([type="submit"])`).

Also, I'm not sure how the settings have anything to do with this since I'm assuming you're logged out?

**Comment by darkred** [comment]
The relevant rule is `background-color: rgb(250, 255, 189) !important;`, i.e.
![2018-08-26_132741](https://user-images.githubusercontent.com/723651/44627284-db271d00-a933-11e8-89ce-1871f7a44287.jpg)

And I mentioned the settings just in case one of them (maybe a beta one enabled in the past) persisted even when logout.
But, to be sure I removed all stackoverflow.com cookies (Cookies, Local/Session Storage), 
but the yellow remains.

**Comment by darkred** [comment]
The relevant rule is `background-color: rgb(250, 255, 189) !important;`, i.e.
![2018-08-26_132741](https://user-images.githubusercontent.com/723651/44627318-5dafdc80-a934-11e8-8ce3-e05fedda9cc4.jpg)

And I mentioned the settings just in case one of them (maybe a beta one enabled in the past) persisted even when logout.
But, to be sure I removed all stackoverflow.com cookies (Cookies, Local/Session Storage), 
but the yellow remains.

**Comment by Mottie** [comment]
There is just something very odd about a "user agent stylesheet" that sets a yellow background color *and* includes an `!important` flag. 

I cannot reproduce this, and I really think there is an extension using `chrome.tab.insertCSS` to add that custom style - that's the only way I can think of to get and see a custom "user agent stylesheet".

Can anyone else reproduce this issue? @silverwind @the-j0k3r?

**Comment by xt0rted** [comment]
@Mottie in Chrome 68 I'm seeing a similar style rule being applied when you use Chrome's autofill service.

```css
input:-webkit-autofill,
textarea:-webkit-autofill,
select:-webkit-autofill {
    background-color: rgb(250, 255, 189) !important;
    background-image: none !important;
    color: rgb(0, 0, 0) !important;
}
```

**Comment by the-j0k3r** [comment]
Werent the autofills green? In any case to redefine you will need to use a keyframes hack.
At least thats the only way I managed this before.
```css
	@-webkit-keyframes autofill {
		to {
			background-color: some color;
			background-image: none;
			color: some color;
		}
	}
	input:-webkit-autofill, input:-webkit-autofill:hover, input:-webkit-autofill:focus,
	textarea:-webkit-autofill, textarea:-webkit-autofill:hover, textarea:-webkit-autofill:focus,
	select:-webkit-autofill, select:-webkit-autofill:hover, select:-webkit-autofill:focus {
		-webkit-animation-name: autofill !important;
		-webkit-animation-fill-mode: both !important;
	}
```

**Comment by Mottie** [comment]
Has this been fixed? Or do we need to try @the-j0k3r's method?

**Comment by darkred** [comment]
> Has this been fixed? 

@Mottie , no, unfortunately [your commit](https://github.com/StylishThemes/StackOverflow-Dark/commit/8f6a6753ddbc986ccf9238d1075e95757de47a39)  didn't fix the issue:

![2018-08-28_200326](https://user-images.githubusercontent.com/723651/44738640-3147bc00-aafe-11e8-9e28-b7b269708987.jpg)

**Comment by darkred** [comment]
I don't know how/where to append to the .usercss . 
I'm not familiar at all with the userscss syntax.

**Comment by darkred** [comment]
Yes, I added something like the following after line 105 of the usercss and yes, it no longer has a yellow background:

````
@-webkit-keyframes autofill {
  {
    background-color: rgba(0, 0, 0, .075) ;
    background-image: none;
    color: rgba(0, 0, 0, .075);
  }
}
input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus,
textarea:-webkit-autofill,
textarea:-webkit-autofill:hover,
textarea:-webkit-autofill:focus,
select:-webkit-autofill,
select:-webkit-autofill:hover,
select:-webkit-autofill:focus {
  -webkit-animation-name: autofill !important;
  -webkit-animation-fill-mode: both !important;
}
```

**Comment by Mottie** [comment]
Why is the background and text the same color? Doesn't that make it unreadable?

**Comment by darkred** [comment]
I used an arbitrary grey/black color just for testing.
Yes, I guess I misunderstood it and the colors should be different -my mistake-, but, it's not unreadable: 
it seems though like that, as I click inside the textbox and the autocomplete suggestion appears, the suggestion text flickers a bit.

**Comment by Mottie** [comment]
Hmm, maybe instead the animation needs to be disabled:

```css
input:-webkit-autofill,
textarea:-webkit-autofill,
select:-webkit-autofill {
  -webkit-animation: none !important;
  -moz-animation: none !important;
  -o-animation: none !important;
  -ms-animation: none !important;
  animation: none !important;
}
```

**Comment by the-j0k3r** [comment]
the full hack is needed last I checked

**Comment by Mottie** [comment]
Ok, please try it now.

**Comment by darkred** [comment]
Unfortunately, it remains yellow:
![2018-08-30_155256](https://user-images.githubusercontent.com/723651/44852840-f617cb00-ac6c-11e8-866f-9d99d1e37be3.jpg)

**Comment by Mottie** [comment]
Blarg! I'll let @the-j0k3r fix it then...

**Comment by Mottie** [comment]
Ok, please test he latest changes. Sorry for taking so long.

**Comment by Mottie** [comment]
Grrr, I used the css that you shared... I still don't see this issue, so I'm going to have to rely on you to help out here.

**Comment by silverwind** [comment]
@Mottie your last commit removed `background-color` and `color`. Is that intentional?

**Comment by Mottie** [comment]
Yeah, since it wasn't included in [this comment](https://github.com/StylishThemes/StackOverflow-Dark/issues/123#issuecomment-416677756).

**Comment by silverwind** [comment]
Ah I see, a horrible hack :)

**Comment by tophf** [comment]
Seeing this issue when editing tags of a question and choosing the dropdown menu with the autofill suggestions. I've fixed it locally via `-webkit-text-fill-color` which wasn't mentioned above AFAICT.

```css
input:-webkit-autofill {
  -webkit-text-fill-color: black !important;
}
```

**Comment by Mottie** [comment]
That's odd, that css makes the text black not the background. So you're seeing an input with a background of `#111` and text that's white?

**Comment by tophf** [comment]
The input is using the standard yellow background when I choose from the dropdown menu.

**Comment by Mottie** [comment]
Can you see what css is adding the yellow background? I still can't reproduce this.

**Comment by tophf** [comment]
It's the built-in webkit/Chrome color. Not sure how to find its CSS. Googling the problem description I see also the following:

```css
input:-webkit-autofill {
    -webkit-box-shadow: 0 0 0px 1000px white inset;
}
```
