### ISSUE TITLE
Please consider hiding by default Hot Network Questions

### ISSUE THREAD

**Issue by vitaly-zdanevich** [StylishThemes/StackOverflow-Dark#132]
So interesting questions distract me. Maybe show them on mouse hover.

**Comment by Mottie** [comment]
Hi @vitaly-zdanevich!

You can add a custom userstyle to do this. Copy/paste the following css into your userstyle manager:

```css
/* ==UserStyle==
@name           Stack Overflow not hot!
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    Hide Hot Network questions
@author         Me
==/UserStyle== */
@-moz-document domain("stackoverflow.com") {
  #hot-network-questions {
    display: none !important;
  }
}
```
