### ISSUE TITLE
Images with transparent backgrounds don't look good

### ISSUE THREAD

**Issue by pnacht** [StylishThemes/StackOverflow-Dark#135]
Images uploaded with transparent backgrounds (which assume the default white StackExchange background) often don't look good.

I currently solve this by adding the following to the script

```
p img {
    background-color:#fff !important;
    padding:1px !important;
}
```

Since the only images which are contained in `p` are in posts, this forces a white background to any user image, while not affecting other images (such as the logo). Obviously images with their own background are unaffected.

I then add a 1px padding just in case the image doesn't have any padding around its own content. Images with their own non-white backgrounds will therefore have a slight padding, but I accept that.

**Comment by Mottie** [comment]
Hi @pnacht!

I have yet to encounter a transparent background image. Would you please share a post?

I think it might be nice to reduce the opacity, and restore it on hover. And what do you think about adding a border instead of padding?

Try this css and let me know if you think it'll work:

```css
  p img {
    background: #fff !important;
    opacity: .5;
    border: #777 2px solid !important;
  }
  p img:hover {
    opacity: 1 !important;
  }
```
