### ISSUE TITLE
StackExchange Site Issues (To Do List)

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/StackOverflow-Dark#14]
- http://pt.stackoverflow.com/
  - [x] Fix logo
- http://ru.stackoverflow.com/
  - [x] Fix logo
- http://ja.stackoverflow.com/
  - [x] Fix logo
- http://wordpress.stackexchange.com/
  - [x] Clean up header (invert?)
  - [x] Fix link colors
  - [ ] Accepted answer style
- http://tex.stackexchange.com/
  - [x] Invert header images
- http://electronics.stackexchange.com/
  - [x] Invert header background?
- http://dba.stackexchange.com/
  - [x] Darker logo
- http://academia.stackexchange.com/
  - [x] Invert header background (buildings at night)
- http://scifi.stackexchange.com/
  - [x] Remove content border?
- http://english.stackexchange.com/
  - [ ] Fix/Darken logo
- http://skeptics.stackexchange.com/
  - [ ] Fix tab hover (questions, tags, users...)
- http://travel.stackexchange.com/
  - [ ] Remove tab background color
  - [ ] Remove votes/answer background color
- http://cstheory.stackexchange.com/
  - [x] Fix logo
  - [x] Fix accepted answer style
- http://mathoverflow.net/
  - [x] Fix logo
- https://stackexchange.com/
  - [x] Darken grid view buttons (https://stackexchange.com/sites#)
  - [x] Darken panels (https://stackexchange.com/newsletters)
  - [x] Darken Feeds (https://stackexchange.com/blogs)

**Comment by guitarjorge24** [comment]
The newsletter panel can be edited at:
#newsletter-ad{
background: url('//cdn.sstatic.net/beta/img/newsletter-ad.png?v=2');
}

**Comment by Mottie** [comment]
Hi @guitarjorge24! I actually meant these newsletters: https://stackexchange.com/newsletters

**Comment by guitarjorge24** [comment]
Oh I see :P Well, it'd be awesome if you could also fix the newsletter I was talking about. It's this one: 
![newsletter](https://cloud.githubusercontent.com/assets/12472021/10428528/193f66ec-70c0-11e5-86ec-4235d0dc3b27.PNG)

**Comment by Mottie** [comment]
Well since that block uses a background image

![newsletter](http://cdn.sstatic.net/stackoverflow/img/newsletter-ad.png?v=2)

the only way to make it not so bright was to turn the opacity way down; we could invert the image, but it would not look good. What exactly were you wanting here?

**Comment by guitarjorge24** [comment]
Well, the way it is right now, the text isn't legible so I think the best option is to edit the image and make it darker or replace the url with just a background color like this:
![newsletter dark](https://cloud.githubusercontent.com/assets/12472021/10505721/72e3ff26-72de-11e5-8b23-55a2c14d5cde.PNG)

**Comment by Mottie** [comment]
Yeah, every StackExchange site has a different "Love this site?" background image... so it might be best to just remove it completely.

**Comment by Mottie** [comment]
Ok, try the change I just made... I'll push it to userstyles.org in the morning if you like it .

**Comment by guitarjorge24** [comment]
Looks great!

**Comment by MrMino** [comment]
New navigation tab colors are inherited from default .css (hurting-my-eyes-white),  so I wrote this. Tested on SO, SO Meta. On the rest of the sites I don't have enough repo (I think?) to have new navigation enabled:
```css
/*New navigation tabs*/
#tabs a, .tabs a, .newnav .tabs-list-container .tabs-list .intellitab a{
    background: #2F2F2F;
}

.newnav .tabs-list-container .tabs-list .intellitab:after{
	display: none;
}

.newnav .tabs-list-container .tabs-list .intellitab .menu-switcher{
	background-color: #2F2F2F;
}

.newnav .tabs-list-container .tabs-list .intellitab .menu-switcher:hover{
	background-color: #1F1F1F;
}
```
