### ISSUE TITLE
Bright lines on "featured on meta" box

### ISSUE THREAD

**Issue by cmeeren** [StylishThemes/StackOverflow-Dark#157]
* **Browser**: Firefox 66.0.3
* **Operating System**: Windows 10
* **Link to page with the issue**: https://stackoverflow.com/questions/22128789/converting-string-to-web-safe-base64-format
* **Screenshot**:

![image](https://user-images.githubusercontent.com/7766733/56827201-6d364b00-685e-11e9-952b-454db1359fe9.png)

**Comment by cmeeren** [comment]
Rule is

```css
.s-sidebarwidget__yellow {
  border-color: #e6dfc6;
  background-color: #FFF8DC;
}
```
