### ISSUE TITLE
The new Tag Synonymns table headers are unstyled

### ISSUE THREAD

**Issue by AfroThundr3007730** [StylishThemes/StackOverflow-Dark#162]
As can be seen [here](https://stackoverflow.com/tags/synonyms). I'm not as familiar with this style's color scheme, but I figure this would work:

```css
.s-table thead th {
  /* background-color: #fafafb; */
  background-color: #111;
}
```
