### ISSUE TITLE
Allow font color customization

### ISSUE THREAD

**Issue by Aran-Fey** [StylishThemes/StackOverflow-Dark#175]
I installed this style today and I soon noticed that the low contrast made my eyes hurt. The grey used for the text is just too similar to the grey used for the background. It's especially bad in chat. It's hard to judge contrast in cropped screenshots, but here they are anyway:

![image](https://user-images.githubusercontent.com/22036272/61993232-17de2580-b069-11e9-87dd-d7fb03e024c4.png)

![image](https://user-images.githubusercontent.com/22036272/61993201-a2725500-b068-11e9-9feb-9c444f686973.png)

![image](https://user-images.githubusercontent.com/22036272/61993198-8ff81b80-b068-11e9-9d7f-66320cf3afa8.png)

![image](https://user-images.githubusercontent.com/22036272/61993225-ed8c6800-b068-11e9-8139-3dea420aeee9.png)

It's especially ridiculous how bright and saturated the green/red/blue in the last screenshot are, compared to the unreadable grey used everywhere else. Why make everything hard to read and then hit me with these color bombs?

I'd like the contrast between background and regular text to be increased, preferably with a user-customizable setting.

**Comment by the-j0k3r** [comment]
@Aran-Fey thanks you for binging this to our attention.

>I installed this style today and I soon noticed that the low contrast made my eyes hurt. The grey used for the text is just too similar to the grey used for the background.

I dont see anything like what you describe,  What I see is the blue link colors arent perhaps what they should be mainly because Im in the process of fixing them.

In a dark style black becomes white and vice-versa, so in any case please indicate in screenshots what should be lighter or darker and please provide a link to page with issue, Ill look into it for sure =)

thanks.

**Comment by Aran-Fey** [comment]
*All* of the grey text should be brighter in my opinion. It's not one specific page that's a problem; this grey text is *everywhere*. `#aaaaaa` is too dark to be easily readable on this background.

> In a dark style black becomes white and vice-versa

`#aaaaaa` is hardly *white*; it's grey. Much like the background.

So I checked the CSS and the text in answers is actually `#bbb`:

![image](https://user-images.githubusercontent.com/22036272/61993232-17de2580-b069-11e9-87dd-d7fb03e024c4.png)
I played around with the color and in the end I bumped up the brightness all the way to `#ddd`, which looks like this:
![image](https://user-images.githubusercontent.com/22036272/61997312-fba9ab00-b09f-11e9-9437-0f77ebc8a430.png)
(It's a bit difficult to see on these cropped screenshots; in reality the difference is more noticeable.)

This text uses `#aaa`:
![image](https://user-images.githubusercontent.com/22036272/61993198-8ff81b80-b068-11e9-9d7f-66320cf3afa8.png)
And I'd much prefer if it was `#ccc`:
![image](https://user-images.githubusercontent.com/22036272/61997343-94402b00-b0a0-11e9-9e80-f749e069565a.png)

This is of course a question of personal preference, but for me the current text color is just too dark - I get a headache if I browse StackOverflow with this theme. I need more contrast between text and background.

**Comment by the-j0k3r** [comment]
I much prefer personally when I dont burn my retinas and can read just fine, again post a link to that page and Ill see if I can find a middle ground. As for making things custom, it would take a great deal of time to re-write style in a manner that accounts for these things. 

At this time Im not prepared to add custom colors given the bad state of the style which has taken considerable ammount of time to get to a half decent place.

**Comment by Aran-Fey** [comment]
Post a link to *what* page? I've said multiple times now that this problem exists *everywhere*.

You're right that there are too many shades of white to make a custom style for every single one, but where's the problem with making 2 or maybe 3 different levels of brightness? *That's* not a lot of work.

1.  Add this:
```css
@advanced dropdown font-brightness "Text brightness" {
  Regular "Regular" <<<EOT
  --font-color-dark2: #999;
  --font-color-dark1: #aaa;
  --font-color-regular: #bbb;
  --font-color-light1: #ccc;
  --font-color-light2: #ddd;
  --font-color-light3: #eee; EOT;
  Light "Light" <<<EOT
  --font-color-dark2: #bbb;
  --font-color-dark1: #c9c9c9;
  --font-color-regular: #ccc;
  --font-color-light1: #cfcfcf;
  --font-color-light2: #ddd;
  --font-color-light3: #fff; EOT;
}
```
2. Add this:
```css
  * {
    /* dont assign any colors here */
    text-shadow: none !important;
    box-shadow: none !important;
    
    /*[[font-brightness]]*/
  }
```
Replace `color: #bbb` with `color: var(--font-color-regular)`, `color: #ccc` with `color: var(--font-color-light1)`, etc.

Took me 30 minutes.
