### ISSUE TITLE
Bright flash on highlighting the target of a link with a #hash

### ISSUE THREAD

**Issue by tophf** [StylishThemes/StackOverflow-Dark#181]
* **Browser**: any
* **Operating System**: any
* **Link to page with the issue**: https://stackoverflow.com/questions/57710254/#57710254
* **Screenshot**:

![Clip619-fs8](https://user-images.githubusercontent.com/1310400/64252888-bab97780-cf24-11e9-8e70-0765195aee09.png)

The offending site script writes to the inline `style` attribute on `#question` div, I can see it if I pause the page in devtools debugger:

```html
<div class="question" data-questionid="57710254" id="question" style="background-color: rgb(245, 183, 95);">
```

The actual RGB values are constantly changed by the page script that imitates the animation in JS.

**Comment by tophf** [comment]
Answer divs can be highlighted too:

```html
<div id="answer-57728843" class="answer" data-answerid="57728843" itemprop="suggestedAnswer" itemscope="" itemtype="http://schema.org/Answer" style="background-color: rgb(35, 35, 35);">
```

**Comment by the-j0k3r** [comment]
Hi, thanks for this ticket.

Could you test this.

```css
	#question[style*="background-color:"] {
		background-color: #321 !important;
	}
	.answer[style*="background-color:"] {
		background-color:  #321 !important;
	}
```

If it works I'll merge it later. Thanks.
