### ISSUE TITLE
visited links in answers are shown dark

### ISSUE THREAD

**Issue by FranklinYu** [StylishThemes/StackOverflow-Dark#234]
* **Browser**: Firefox
* **Operating System**: macOS
* **Link to page with the issue**: https://unix.stackexchange.com/questions/9743/numbering-convention-for-the-linux-kernel
* **Screenshot**:
![圖片](https://user-images.githubusercontent.com/3153452/123505997-c9e84880-d616-11eb-9437-64e26ec66422.png)

Possibly affected style from Stack Exchange:

```css
.s-prose a:not(.post-tag):not(.s-tag):not(.badge-tag):not(.s-link__visited):not(.s-btn):not(.s-editor-btn):visited,
.comment-copy a:visited {
  color:var(--theme-link-color-visited)
}
```

I guess we might need some `!important` somewhere.

Note: I enabled native dark theme in Stack Overflow, which might affect the value of `--theme-link-color-visited`.

**Comment by the-j0k3r** [comment]
Would you try adding to your local install of style `    --theme-link-color-visited: /*[[visited-color]]*/ !important;` over  `    --theme-footer-link-color: **#aaa;` in main `  body[class*="theme-"], body {` e.g.
```css
  body[class*="theme-"], body {
    --theme-link-color-visited: /*[[visited-color]]*/ !important;
    --theme-footer-link-color: #aaa;
    ...
    ...
    ...
    ...
}
```

try with and without `!important` I would prefer not to use it unless necessary.

Let me know.

Thanks.

**Comment by the-j0k3r** [comment]
also please note.

`  .s-prose a:not(.post-tag):not(.s-tag):not(.badge-tag):not(.s-link__visited):not(.s-btn):not(.s-editor-btn), .comment-copy a {
` **is not visited color** as the exceptions `:not` indicate.

At best this would be 

```css
  .s-prose a:not(.post-tag):not(.s-tag):not(.badge-tag):not(.s-link__visited):not(.s-btn):not(.s-editor-btn), .comment-copy a {
    color: /*[[base-color]]*/
  }
```
